/**
 * Near-Miss Detector — outcome-based only.
 *
 * Reads the ACTUAL reel result. Never fabricates or manipulates outcomes.
 *
 * A near-jackpot is when 3 or 4 out of 5 jackpot symbols land on a payline,
 * but NOT all 5 (that would be an actual jackpot win).
 *
 * Per-game configuration controls which symbols count and what threshold triggers.
 *
 * FAIRNESS GUARANTEE: This function is read-only. It has no side effects on
 * RNG, payouts, balance, or jackpot probability.
 */

import type { SpinGrid } from './rng';
import type { SymbolId } from '../config/symbols';
import { PAYLINES } from './paylines';

// ── Per-game near-miss config ──────────────────────────────────────────────

export interface NearJackpotConfig {
  gameId: string;
  gameName: string;                 // human-readable name for toast
  jackpotSymbols: SymbolId[];       // symbols that count toward jackpot
  nearMissThreshold: number;        // min matches to qualify (e.g. 3 out of 5)
  requiredForJackpot: number;       // matches needed for the actual jackpot
  enableNearJackpotNotification: boolean;
}

export const NEAR_JACKPOT_CONFIGS: Record<string, NearJackpotConfig> = {
  'cyber-strike-777': {
    gameId: 'cyber-strike-777',
    gameName: 'Mega Jackpot',
    jackpotSymbols: ['seven', 'wild'],
    nearMissThreshold: 3,
    requiredForJackpot: 5,
    enableNearJackpotNotification: true,
  },
  'electric-storm': {
    gameId: 'electric-storm',
    gameName: 'Electric Jackpot',
    jackpotSymbols: ['storm_eye', 'wild'],
    nearMissThreshold: 3,
    requiredForJackpot: 5,
    enableNearJackpotNotification: true,
  },
  'quantum-vault': {
    gameId: 'quantum-vault',
    gameName: 'Quantum Jackpot',
    jackpotSymbols: ['vault', 'wild'],
    nearMissThreshold: 3,
    requiredForJackpot: 5,
    enableNearJackpotNotification: true,
  },
  'dark-matter-reels': {
    gameId: 'dark-matter-reels',
    gameName: 'Dark Matter Jackpot',
    jackpotSymbols: ['dark_crystal', 'wild'],
    nearMissThreshold: 3,
    requiredForJackpot: 5,
    enableNearJackpotNotification: true,
  },
  'neon-samurai': {
    gameId: 'neon-samurai',
    gameName: 'Samurai Jackpot',
    jackpotSymbols: ['shogun', 'wild'],
    nearMissThreshold: 3,
    requiredForJackpot: 5,
    enableNearJackpotNotification: true,
  },
};

// ── Result types ───────────────────────────────────────────────────────────

export interface NearMissResult {
  isNearMiss: boolean;
  jackpotSymbol: SymbolId | null;
  matchedPositions: number;
  requiredPositions: number;
  gameName: string;
  message: string;
}

// ── Detection function ─────────────────────────────────────────────────────

/**
 * Analyse the actual spin grid for a near-jackpot result.
 * Returns isNearMiss=false for any ordinary outcome.
 *
 * @param grid   — the reel result as generated by the RNG (read-only)
 * @param gameId — used to look up per-game configuration
 */
export function detectNearMiss(grid: SpinGrid, gameId?: string): NearMissResult {
  const noResult: NearMissResult = {
    isNearMiss: false,
    jackpotSymbol: null,
    matchedPositions: 0,
    requiredPositions: 5,
    gameName: '',
    message: '',
  };

  const config = gameId ? NEAR_JACKPOT_CONFIGS[gameId] : null;
  if (config && !config.enableNearJackpotNotification) return noResult;

  // Which symbols count as jackpot symbols for this game
  const jackpotSymbols: SymbolId[] = config
    ? config.jackpotSymbols
    : ['seven', 'wild', 'vault', 'shogun', 'storm_eye', 'dark_crystal'];

  const threshold = config?.nearMissThreshold ?? 3;
  const required  = config?.requiredForJackpot ?? 5;
  const gameName  = config?.gameName ?? 'Mega Jackpot';

  for (const payline of PAYLINES) {
    const symbols: SymbolId[] = payline.map((row, col) => grid[col][row]);

    for (const jackpotSym of jackpotSymbols) {
      if (jackpotSym === 'wild') continue; // wilds are counted via the primary symbol

      const primarySym = jackpotSym;
      const matches = symbols.filter((s) => s === primarySym || s === 'wild').length;

      // Must meet near-miss threshold but NOT be a full jackpot win
      if (matches >= threshold && matches < required) {
        return {
          isNearMiss: true,
          jackpotSymbol: primarySym,
          matchedPositions: matches,
          requiredPositions: required,
          gameName,
          message: buildMessage(matches, required, gameName),
        };
      }
    }
  }

  return noResult;
}

function buildMessage(matched: number, required: number, gameName: string): string {
  const missing = required - matched;
  const missingWord = missing === 1 ? 'one symbol' : `${missing} symbols`;

  const templates = [
    `${matched} jackpot symbols! Just ${missingWord} away from the ${gameName}.`,
    `SO CLOSE! You were ${missingWord} away from triggering the ${gameName}.`,
    `NEAR JACKPOT! ${matched}/${required} symbols landed — ${missingWord} short.`,
  ];

  return templates[Math.floor(Math.random() * templates.length)];
}
